language: csharp
mono: none
dist: trusty
dotnet: 2.0.0
sudo: required
script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet test -c Release ./tests
deploy:
  provider: azure_web_apps
  verbose: true